services:
  _defaults:
    autowire: true

  App\InterInvest\Company\Application\Query\:
    resource: '%kernel.project_dir%/src/InterInvest/Company/Application/Query/*Handler.php'
    tags:
      - { name: messenger.message_handler, bus: query.bus }

  App\InterInvest\Company\Application\Command\:
    resource: '%kernel.project_dir%/src/InterInvest/Company/Application/Command/*Handler.php'
    tags:
      - { name: messenger.message_handler, bus: command.bus }

  App\InterInvest\Company\UI\Console\Command\:
    resource: '%kernel.project_dir%/src/InterInvest/Company/UI/Console/Command'
    tags:
      - { name: console.command }

  App\InterInvest\Company\UI\Web\Controller\:
    resource: '%kernel.project_dir%/src/InterInvest/Company/UI/Web/Controller'
    tags:
      - { name: controller.service_arguments }
      - { name: container.service_subscriber }


  App\InterInvest\Company\UI\Web\Form\CompanyFormType:
    tags: ['form.type']
    arguments:
      - '@App\InterInvest\Company\Domain\LegalStatusRepositoryInterface'

  App\InterInvest\Company\UI\Web\Form\CompanyUpdateFormType:
    tags: [ 'form.type' ]
    arguments:
      - '@App\InterInvest\Company\Domain\LegalStatusRepositoryInterface'


  App\InterInvest\Company\Domain\AddressRepositoryInterface:
    class: App\InterInvest\Company\Infrastructure\Doctrine\Persistence\Repository\AddressRepository

  App\InterInvest\Company\Domain\LegalStatusRepositoryInterface:
    class: App\InterInvest\Company\Infrastructure\Doctrine\Persistence\Repository\LegalStatusRepository

  App\InterInvest\Company\Domain\LegalStatusInitiator: ~

  App\InterInvest\Company\Domain\CompanyRepositoryInterface:
    class: App\InterInvest\Company\Infrastructure\Doctrine\Persistence\Repository\CompanyRepository


  App\InterInvest\Company\Application\Command\CommandBusInterface:
    class: App\InterInvest\Company\Messenger\MessengerCommandBus
    arguments:
      - '@command.bus'

  App\InterInvest\Company\Application\Query\QueryBusInterface:
    class: App\InterInvest\Company\Messenger\MessengerQueryBus
    arguments:
      - '@query.bus'

  App\InterInvest\Company\Application\Event\EventBusInterface:
    class: App\InterInvest\Company\Messenger\MessengerEventBus
    arguments:
      - '@event.bus'